default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40958_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40958_test
#
production:
  <<: *default
  database: furima_40958_production
  username: furima_40958
  password: <%= ENV["FURIMA_40958_DATABASE_PASSWORD"] %>
